### ISSUE TITLE
when user clicks on login button of Signup page of user homepage then it drags to home page rather than drag to login page

### ISSUE THREAD

**Issue by pankajmahato907** [enochanok/gantavya#12]
In User homepage, when user clicks on login button of Signup then it drags to home page rather than drag to login page. Soo It should be corrected as user clicks on login button it should be drag to the login page.

<img width="903" alt="image" src="https://github.com/enochanok/gantavya/assets/127825279/87ed5520-25df-496f-936e-1b531110d78b">

https://github.com/enochanok/gantavya/assets/127825279/4634dc3d-c4af-4b96-909d-cb0d1485c6cf

**Comment by SamirThapa01** [comment]
the issue has been solved

https://github.com/enochanok/gantavya/assets/164458355/aae5d2f7-9fbb-4b9d-9263-15161efee486

**Comment by SamirThapa01** [comment]
Solved
