### ISSUE TITLE
Bug in Footer

### ISSUE THREAD

**Issue by pankajmahato907** [enochanok/gantavya#19]
When user visits on footer of User Homepage, It looks double footer page so it should be solve.
<img width="917" alt="Footer Error" src="https://github.com/enochanok/gantavya/assets/127825279/67a9d93f-02bf-4772-96e6-7dc1013e8f51">

**Comment by SamirThapa01** [comment]
Issue solved
![image](https://github.com/enochanok/gantavya/assets/164458355/8a7a23ec-e107-4c52-8836-6a69ae159805)
