### ISSUE TITLE
When user click on quick links designed on footer of User UI such as Contacts or About  us page, It only navigate to homepage rather than going to going on next page

### ISSUE THREAD

**Issue by pankajmahato907** [enochanok/gantavya#20]
Actual Behavior:
Clicking upon the quick links of User interface, It only redirected to Home page.

Expected Behavior:
Clicking upon the quick links of User interface, It should be navigate to the respective page like 
if user click Contacts link then it should be redirected to contacts page like wise if user clicks 
about us page then it should be redirected to about us page

![image](https://github.com/enochanok/gantavya/assets/127825279/aa92e103-6acd-4cfc-b77e-48b7474b2225)

**Comment by SamirThapa01** [comment]
solved

https://github.com/enochanok/gantavya/assets/164458355/21d9839b-561f-40d5-a89f-aa58460b0917
