### ISSUE TITLE
The Signup page layout is not fitting with the website which results in improper  display. Also the Home button overlaps the signup page which obstructs user interaction  and navigation.

### ISSUE THREAD

**Issue by pankajmahato907** [enochanok/gantavya#21]
Actual Behavior:
The Signup page appears to be improperly displayed within the website layout and 
home button overlaps with the signup page.
Expected Behavior: -
The signup page should be fit within the website layout maintaining proper alignment 
and home button should not overlap with any page elements

![image](https://github.com/enochanok/gantavya/assets/127825279/001b7d55-e01e-4add-80c5-b4304b8cbc0e)

**Comment by Ayushyonghang** [comment]
bug solved in https://github.com/enochanok/gantavya/commit/a85f8f7ba392c576c162a0b08723e7ba46f95a18 commit
