### ISSUE TITLE
When User login the system, The system show signup Successful instead of showing Login Successful as a validation.

### ISSUE THREAD

**Issue by pankajmahato907** [enochanok/gantavya#22]
Actual Behavior: When a user login into the system, instead of displaying "Login Successful" as a validation message, the system shows "Signup Successful".

Expected Behavior: Upon successful login, the system should display a validation message indicating "Login Successful". This is the expected behavior to inform the user that their login attempt was successful.
![image](https://github.com/enochanok/gantavya/assets/127825279/96bc57a8-e5df-4803-b2d9-9a0566439b1e)

**Comment by SamirThapa01** [comment]
![image](https://github.com/enochanok/gantavya/assets/164458355/3c24409a-b368-4ace-8872-bb31c9963931)
![image](https://github.com/enochanok/gantavya/assets/164458355/105bfb70-92b8-44a0-9ea5-426bb71a3d4c)
solved

**Comment by SamirThapa01** [comment]
solved
